//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.DesignDB.Entity
{
    [Table("DesignSubject")]
    public partial class DesignSubjectEntity
    {

        /// <summary>
        /// 自增长ID
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 应用ID
        /// </summary>
        public int AppId { get; set; }

        /// <summary>
        /// 主体ID
        /// </summary>
        public int SubjectId { get; set; }

        /// <summary>
        /// 主体名称，用于编程
        /// </summary>
        [Required]
        [StringLength(100)]
        public string SubjectName { get; set; }

        /// <summary>
        /// 主体名称，用于展示，后续考虑国际化，可能需要将这个摘出去
        /// </summary>
        [Required]
        [StringLength(100)]
        public string SubjectTitle { get; set; }

        /// <summary>
        /// 数据库ID
        /// </summary>
        public int DatabaseId { get; set; }

        /// <summary>
        /// 表ID
        /// </summary>
        public int TableId { get; set; }

        /// <summary>
        /// 数据状态
        /// </summary>
        public int DataStatus { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CreateUser { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最后更信任
        /// </summary>
        [Required]
        [StringLength(50)]
        public string LastUpdateUser { get; set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime LastUpdateTime { get; set; }
    }
}