//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.DesignDB.Entity
{
    /// <summary>
    /// 外键表
    /// </summary>
    [Table("DesignForeignKey")]
    public partial class DesignForeignKeyEntity
    {

        /// <summary>
        /// 自增长ID
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 数据库ID
        /// </summary>
        public int DatabaseId { get; set; }

        /// <summary>
        /// 主表
        /// </summary>
        public int MainTableId { get; set; }

        /// <summary>
        /// 主表字段
        /// </summary>
        public int MainFieldId { get; set; }

        /// <summary>
        /// 从表
        /// </summary>
        public int ForeignTableId { get; set; }

        /// <summary>
        /// 从表字段
        /// </summary>
        public int ForeignFieldId { get; set; }

        /// <summary>
        /// 数据状态
        /// </summary>
        public int DataStatus { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CreateUser { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最后更新人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string LastUpdateUser { get; set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime LastUpdateTime { get; set; }
    }
}