//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.DesignDB.Entity
{
    [Table("DesignAppDatabase")]
    public partial class DesignAppDatabaseEntity
    {

        public int Id { get; set; }

        public int AppId { get; set; }

        public int DatabaseId { get; set; }

        public int DataStatus { get; set; }

        [Required]
        [StringLength(50)]
        public string CreateUser { get; set; }

        public DateTime CreateTime { get; set; }

        [Required]
        [StringLength(50)]
        public string LastUpdateUser { get; set; }

        public DateTime LastUpdateTime { get; set; }
    }
}