//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.DesignDB.Entity
{
    [Table("DesignDatabase")]
    public partial class DesignDatabaseEntity
    {

        /// <summary>
        /// 自增长ID
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 数据库标识
        /// </summary>
        public int DatabaseId { get; set; }

        /// <summary>
        /// 数据库名称
        /// </summary>
        [Required]
        [StringLength(100)]
        public string DatabaseName { get; set; }

        /// <summary>
        /// 数据库类型 1.SqlServer 2.MySql 3.Sqlite 4.Access
        /// </summary>
        public int DatabaseTypeId { get; set; }

        /// <summary>
        /// 数据库用途，描述等
        /// </summary>
        [Required]
        [StringLength(200)]
        public string Description { get; set; }

        /// <summary>
        /// 数据状态 1.有效 2.已删除
        /// </summary>
        public int DataStatus { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CreateUser { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最后更新人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string LastUpdateUser { get; set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime LastUpdateTime { get; set; }
    }
}