//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.DesignDB.Entity
{
    /// <summary>
    /// 用于实现业务逻辑的ID自增长
    /// </summary>
    [Table("Increment")]
    public partial class IncrementEntity
    {

        /// <summary>
        /// 自增长ID
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 项目键，需要实现定义好
        /// </summary>
        public int ItemKey { get; set; }

        /// <summary>
        /// 当前可用的项目ID，要记得在代码里面做 i++ 的操作，不要手动修改
        /// </summary>
        public int ItemId { get; set; }
    }
}