//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由EntityGen生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Savory.Repository.DesignDB.Entity
{
    [Table("OpLog")]
    public partial class OpLogEntity
    {

        /// <summary>
        /// 自增长主键
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// 表名称
        /// </summary>
        [Required]
        [StringLength(50)]
        public string TableName { get; set; }

        /// <summary>
        /// 操作类型 1.增加 2.修改 3.删除(DataStatus设为2)
        /// </summary>
        public int ActionType { get; set; }

        /// <summary>
        /// 旧数据
        /// </summary>
        [Required]
        public string OldEntity { get; set; }

        /// <summary>
        /// 新数据
        /// </summary>
        [Required]
        public string NewEntity { get; set; }

        /// <summary>
        /// 数据状态 1.有效 2.无效
        /// </summary>
        public int DataStatus { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string CreateUser { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreateTime { get; set; }

        /// <summary>
        /// 最后更新人
        /// </summary>
        [Required]
        [StringLength(50)]
        public string LastUpdateUser { get; set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        public DateTime LastUpdateTime { get; set; }
    }
}